import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const input = resolve(root, "catalogs/core.json");
const output = resolve(here, "../src/generated/catalog.ts");
const catalog = JSON.parse(await readFile(input, "utf8"));
const generatedCatalog = await readFile(resolve(root, "python/indexer/generated_catalog.py"), "utf8");
const catalogHash = generatedCatalog.match(/CATALOG_HASH = ['\"]([^'\"]+)['\"]/)?.[1];
if (!catalogHash) throw new Error("generated catalog hash is missing");
const source = `// Generated by ui/scripts/generate-catalog.mjs. Do not edit by hand.\nexport const CORE_CATALOG = ${JSON.stringify({ ...catalog, catalog_hash: catalogHash }, null, 2)} as const;\n`;
await writeFile(output, source, "utf8");
