// Generated by scripts/generate_contracts.py; do not edit.
#pragma once

#include <string_view>

namespace cidx::version {

inline constexpr std::string_view kProductVersion = "0.53.0";
inline constexpr std::string_view kBaseProductVersion = "0.53.0";
inline constexpr std::string_view kFullProductVersion = "0.53.0";
inline constexpr std::string_view kReleaseChannel = "stable";
inline constexpr std::string_view kPrerelease = {};

inline constexpr int kDatabaseSchemaVersion = 40;
inline constexpr int kDatabaseMigrationFloor = 2;
inline constexpr int kDatabaseReaderMin = 40;
inline constexpr int kDatabaseReaderMax = 40;

inline constexpr int kCatalogVersion = 1;
inline constexpr std::string_view kCatalogHash =
    "sha256:d5968666092d734cb15a81fddc46d4781f61b894e19cf5649b6fd5b6f2a510e9";
inline constexpr int kArtifactVersion = 1;
inline constexpr int kArtifactReaderMin = 1;
inline constexpr int kArtifactReaderMax = 1;
inline constexpr int kApiVersion = 1;
inline constexpr int kApiReaderMin = 1;
inline constexpr int kApiReaderMax = 1;

} // namespace cidx::version
