// Generated by scripts/generate_catalogs.py; DO NOT EDIT.
#pragma once
#include <array>
#include <string_view>
namespace cidx::catalog {
struct ExtensionRelation { std::string_view qualified_name; std::string_view package; std::string_view id; std::string_view name; std::string_view layer; std::string_view source; std::string_view target; std::string_view inverse; std::string_view traversal; std::string_view evidence; std::string_view evidence_capabilities; std::string_view completeness; };
inline constexpr std::string_view kExtensionCatalogHash = "38453dfc66a3cb7c2e31483cb711cb8a99231a531557e30a46c7d81d0e84ef7b";
inline constexpr std::array<ExtensionRelation, 1> kExtensionRelations = {{
    {.qualified_name = "test.extension/relation/taints", .package = "test.extension", .id = "relation/taints", .name = "taints", .layer = "symbol", .source = "symbol.declaration", .target = "symbol.declaration", .inverse = "tainted_by", .traversal = "out|in", .evidence = "derived", .evidence_capabilities = "derived|proof", .completeness = "partial"},
}};
}
