# Generated by scripts/generate_catalogs.py; DO NOT EDIT.
CATALOG_HASH = 'be3a97cf69140080586a079a27a97da7816455f477ce56435ee91c600cc993fc'
EXTENSION_RELATIONS = {'test.extension/relation/taints': {'package': 'test.extension', 'id': 'relation/taints', 'name': 'taints', 'layer': 'symbol', 'source': 'symbol.declaration', 'target': 'symbol.declaration', 'inverse': 'tainted_by', 'traversal': ['out', 'in'], 'evidence': 'derived', 'evidence_capabilities': ['derived', 'proof'], 'completeness': 'partial'}}
EXTENSION_RELATION_CATALOG = tuple(EXTENSION_RELATIONS.items())
