# Generated by scripts/generate_catalogs.py; DO NOT EDIT.
CATALOG_HASH = '01d0d1896e335566cb40599c1f57926f41f1fd4370cbc13703e0510316d8d287'
EXTENSION_RELATIONS = {'test.extension/relation/taints': {'package': 'test.extension', 'id': 'relation/taints', 'name': 'taints', 'layer': 'symbol', 'source': 'symbol.declaration', 'target': 'symbol.declaration', 'inverse': 'tainted_by', 'traversal': ['out', 'in'], 'evidence': 'derived', 'evidence_capabilities': ['derived', 'proof'], 'completeness': 'partial'}}
EXTENSION_RELATION_CATALOG = tuple(EXTENSION_RELATIONS.items())
