# Generated by scripts/generate_catalogs.py; DO NOT EDIT.
CATALOG_HASH = '3337824260ee0afe1260859b6be88e6fb8280852fd736cde5e12cca5c3847ba4'
EXTENSION_RELATIONS = {'test.extension/relation/taints': {'package': 'test.extension', 'id': 'relation/taints', 'name': 'taints', 'layer': 'symbol', 'source': 'symbol.declaration', 'target': 'symbol.declaration', 'inverse': 'tainted_by', 'traversal': ['out', 'in'], 'evidence': 'derived', 'evidence_capabilities': ['derived', 'proof'], 'completeness': 'partial'}}
EXTENSION_RELATION_CATALOG = tuple(EXTENSION_RELATIONS.items())
