// Generated by scripts/generate_contracts.py; do not edit.
#pragma once

#include <string_view>

namespace cidx::version {

inline constexpr std::string_view kProductVersion = "0.53.0";
inline constexpr std::string_view kBaseProductVersion = "0.53.0";
inline constexpr std::string_view kFullProductVersion = "0.53.0";
inline constexpr std::string_view kReleaseChannel = "stable";
inline constexpr std::string_view kPrerelease = {};

inline constexpr int kDatabaseSchemaVersion = 39;
inline constexpr int kDatabaseMigrationFloor = 2;
inline constexpr int kDatabaseReaderMin = 39;
inline constexpr int kDatabaseReaderMax = 39;

inline constexpr int kCatalogVersion = 1;
inline constexpr std::string_view kCatalogHash =
    "sha256:6a0d9c70c30ea7954b6866b4345b2abc34936fd594acf51d088cb6232916e385";
inline constexpr int kArtifactVersion = 1;
inline constexpr int kArtifactReaderMin = 1;
inline constexpr int kArtifactReaderMax = 1;
inline constexpr int kApiVersion = 1;
inline constexpr int kApiReaderMin = 1;
inline constexpr int kApiReaderMax = 1;

} // namespace cidx::version
