// Generated by scripts/generate_contracts.py; do not edit.
#pragma once

#include <string_view>

namespace cidx::version {

inline constexpr std::string_view kProductVersion = "0.53.0";
inline constexpr std::string_view kBaseProductVersion = "0.53.0";
inline constexpr std::string_view kFullProductVersion = "0.53.0";
inline constexpr std::string_view kReleaseChannel = "stable";
inline constexpr std::string_view kPrerelease = {};

inline constexpr int kDatabaseSchemaVersion = 39;
inline constexpr int kDatabaseMigrationFloor = 2;
inline constexpr int kDatabaseReaderMin = 39;
inline constexpr int kDatabaseReaderMax = 39;

inline constexpr int kCatalogVersion = 1;
inline constexpr std::string_view kCatalogHash =
    "sha256:2537264091da445f4ee39943f985fc269577341a33a4acaad4a5020db9a0fd83";
inline constexpr int kArtifactVersion = 1;
inline constexpr int kArtifactReaderMin = 1;
inline constexpr int kArtifactReaderMax = 1;
inline constexpr int kApiVersion = 1;
inline constexpr int kApiReaderMin = 1;
inline constexpr int kApiReaderMax = 1;

} // namespace cidx::version
