#!/usr/bin/env python3
"""Generate the cross-language version contract from version.json."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "spec/platform/version.json"
CPP_OUTPUT = ROOT / "src/cli/version.hpp"
PY_OUTPUT = ROOT / "python/indexer/_version.py"
SEMVER = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")


def load_contract() -> dict:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if data.get("format_version") != 1:
        raise ValueError("unsupported version contract format")
    product = data["product"]
    if not SEMVER.fullmatch(product["version"]):
        raise ValueError(f"product.version is not SemVer: {product['version']!r}")
    if product["channel"] not in {"stable", "nightly", "dev"}:
        raise ValueError(f"unsupported product channel: {product['channel']!r}")
    prerelease = product["prerelease"]
    if prerelease is not None:
        if not isinstance(prerelease, dict) or not re.fullmatch(
            r"[a-z][0-9]+", str(prerelease.get("tag", ""))
        ):
            raise ValueError("prerelease must be null or {\"tag\": \"rc1\"}")
    for family in ("database", "catalog", "artifact", "api"):
        value = (
            data[family]["schema_version"]
            if family == "database"
            else data[family]["version"]
        )
        if int(value) < 1:
            raise ValueError(f"{family} version must be positive")
    return data


def catalog_hash(data: dict) -> str:
    digest = hashlib.sha256()
    for relative in sorted(data["catalog"]["inputs"]):
        path = ROOT / relative
        if not path.is_file():
            raise ValueError(f"catalog input does not exist: {relative}")
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return f"sha256:{digest.hexdigest()}"


def full_version(data: dict) -> str:
    prerelease = data["product"]["prerelease"]
    if prerelease is None:
        return data["product"]["version"]
    return f"{data['product']['version']}-{prerelease['tag']}"


def render_cpp(data: dict, digest: str) -> str:
    product = data["product"]
    database = data["database"]
    prerelease = (product["prerelease"] or {}).get("tag", "")
    return """// Generated by scripts/generate_contracts.py; do not edit.
#pragma once

#include <string_view>

namespace cidx::version {{

inline constexpr std::string_view kProductVersion = "{product_version}";
inline constexpr std::string_view kFullProductVersion = "{full_version}";
inline constexpr std::string_view kReleaseChannel = "{channel}";
inline constexpr std::string_view kPrerelease = {prerelease_value};

inline constexpr int kDatabaseSchemaVersion = {schema_version};
inline constexpr int kDatabaseMigrationFloor = {migration_floor};
inline constexpr int kDatabaseReaderMin = {reader_min};
inline constexpr int kDatabaseReaderMax = {reader_max};

inline constexpr int kCatalogVersion = {catalog_version};
inline constexpr std::string_view kCatalogHash = "{catalog_hash}";
inline constexpr int kArtifactVersion = {artifact_version};
inline constexpr int kArtifactReaderMin = {artifact_reader_min};
inline constexpr int kArtifactReaderMax = {artifact_reader_max};
inline constexpr int kApiVersion = {api_version};
inline constexpr int kApiReaderMin = {api_reader_min};
inline constexpr int kApiReaderMax = {api_reader_max};

}} // namespace cidx::version
""".format(
        product_version=product["version"],
        full_version=full_version(data),
        channel=product["channel"],
        prerelease=prerelease,
        prerelease_value="{}" if not prerelease else f'"{prerelease}"',
        schema_version=database["schema_version"],
        migration_floor=database["migration_floor"],
        reader_min=database["reader_min"],
        reader_max=database["reader_max"],
        catalog_version=data["catalog"]["version"],
        catalog_hash=digest,
        artifact_version=data["artifact"]["version"],
        artifact_reader_min=data["artifact"]["reader_min"],
        artifact_reader_max=data["artifact"]["reader_max"],
        api_version=data["api"]["version"],
        api_reader_min=data["api"]["reader_min"],
        api_reader_max=data["api"]["reader_max"],
    )


def render_python(data: dict, digest: str) -> str:
    product = data["product"]
    database = data["database"]
    prerelease = (product["prerelease"] or {}).get("tag", "")
    return """\"\"\"Generated by scripts/generate_contracts.py; do not edit.\"\"\"

__version__ = "{product_version}"
FULL_VERSION = "{full_version}"
RELEASE_CHANNEL = "{channel}"
PRERELEASE = "{prerelease}"
DATABASE_SCHEMA_VERSION = {schema_version}
DATABASE_MIGRATION_FLOOR = {migration_floor}
DATABASE_READER_MIN = {reader_min}
DATABASE_READER_MAX = {reader_max}
CATALOG_VERSION = {catalog_version}
CATALOG_HASH = "{catalog_hash}"
ARTIFACT_VERSION = {artifact_version}
ARTIFACT_READER_MIN = {artifact_reader_min}
ARTIFACT_READER_MAX = {artifact_reader_max}
API_VERSION = {api_version}
API_READER_MIN = {api_reader_min}
API_READER_MAX = {api_reader_max}
""".format(
        product_version=product["version"],
        full_version=full_version(data),
        channel=product["channel"],
        prerelease=prerelease,
        schema_version=database["schema_version"],
        migration_floor=database["migration_floor"],
        reader_min=database["reader_min"],
        reader_max=database["reader_max"],
        catalog_version=data["catalog"]["version"],
        catalog_hash=digest,
        artifact_version=data["artifact"]["version"],
        artifact_reader_min=data["artifact"]["reader_min"],
        artifact_reader_max=data["artifact"]["reader_max"],
        api_version=data["api"]["version"],
        api_reader_min=data["api"]["reader_min"],
        api_reader_max=data["api"]["reader_max"],
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    try:
        data = load_contract()
        digest = catalog_hash(data)
        expected = {CPP_OUTPUT: render_cpp(data, digest), PY_OUTPUT: render_python(data, digest)}
        stale = [
            path
            for path, content in expected.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if args.check:
            for path in stale:
                print(f"stale generated contract: {path.relative_to(ROOT)}", file=sys.stderr)
            return int(bool(stale))
        for path, content in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        return 0
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"contract generation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
