-- Generated by scripts/generate_catalogs.py; DO NOT EDIT.
INSERT OR IGNORE INTO symbol_kind(id,name) VALUES
  (2,"struct"),
  (3,"union"),
  (4,"class"),
  (5,"enum"),
  (6,"member"),
  (7,"enum-constant"),
  (8,"function"),
  (9,"variable"),
  (20,"typedef"),
  (21,"method"),
  (22,"namespace"),
  (24,"constructor"),
  (25,"destructor"),
  (30,"function-template"),
  (31,"class-template"),
  (36,"type-alias"),
  (501,"macro");
INSERT OR IGNORE INTO edge_kind(id,name) VALUES
  (1,"calls"),
  (2,"inherits"),
  (3,"contains"),
  (4,"specializes"),
  (5,"instantiates"),
  (6,"overrides"),
  (7,"uses"),
  (8,"field_of"),
  (9,"method_of"),
  (10,"construct-value"),
  (11,"construct-temp"),
  (12,"construct-heap"),
  (13,"construct-copy"),
  (14,"construct-move"),
  (15,"factory-construct"),
  (16,"destroy"),
  (17,"friend"),
  (18,"dispatch_calls"),
  (19,"alias_of"),
  (20,"of_type");
INSERT OR IGNORE INTO entity_edge_kind(id,name) VALUES
  (1,"generalizes"),
  (2,"implements"),
  (3,"specializes"),
  (4,"composes"),
  (5,"aggregates"),
  (6,"associates"),
  (7,"creates"),
  (8,"uses"),
  (9,"destroys"),
  (10,"befriends"),
  (11,"instantiates"),
  (12,"declares");
INSERT OR IGNORE INTO entity_kind(id,name) VALUES
  (0,"other"),
  (1,"class"),
  (2,"abstract_class"),
  (3,"interface"),
  (4,"union"),
  (5,"enum"),
  (6,"class_template"),
  (7,"abstract_class_template"),
  (8,"interface_template"),
  (9,"namespace");
INSERT OR IGNORE INTO type_kind(id,name) VALUES
  (1,"builtin"),
  (2,"record"),
  (3,"enum"),
  (4,"alias"),
  (5,"pointer"),
  (6,"lvalue-reference"),
  (7,"rvalue-reference"),
  (8,"array"),
  (9,"function"),
  (10,"template-param"),
  (11,"other"),
  (12,"member-data-pointer"),
  (13,"member-function-pointer");
INSERT OR IGNORE INTO type_edge_kind(id,name) VALUES
  (1,"pointee"),
  (2,"element_type"),
  (3,"alias_of"),
  (4,"return_type"),
  (5,"param_type"),
  (6,"template_argument_type"),
  (7,"member_owner"),
  (8,"member_component");
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:1",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site","declaration"],"inverse":"called_by","name":"calls","source":"symbol.callable","target":"symbol.callable","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:2",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"subclasses","name":"inherits","source":"symbol.record","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:3",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"contained_by","name":"contains","source":"symbol.scope","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:4",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration","reference_site"],"inverse":"specialized_by","name":"specializes","source":"symbol.declaration","target":"symbol.template","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:5",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration","reference_site"],"inverse":"instantiated_by","name":"instantiates","source":"symbol.declaration","target":"symbol.template","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:6",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"overridden_by","name":"overrides","source":"symbol.method","target":"symbol.method","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:7",'{"completeness":"partial","evidence":"reference_site","evidence_capabilities":["reference_site","call_site"],"inverse":"used_by","name":"uses","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:8",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"fields","name":"field_of","source":"symbol.member","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:9",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"methods","name":"method_of","source":"symbol.method","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:10",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"construct-value","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:11",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"construct-temp","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:12",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"construct-heap","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:13",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"construct-copy","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:14",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"construct-move","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:15",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","name":"factory-construct","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:16",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"destroyed_by","name":"destroy","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:17",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"befriended_by","name":"friend","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:18",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site","derived"],"inverse":"dispatch_callers","name":"dispatch_calls","source":"symbol.callable","target":"symbol.callable","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:19",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"aliased_by","name":"alias_of","source":"symbol.alias","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:20",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"typed_by","name":"of_type","source":"symbol.declaration","target":"type","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:1",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"specialized_by","name":"generalizes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:2",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"implemented_by","name":"implements","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:3",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"specialized_by","name":"specializes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:4",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"composed_by","name":"composes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:5",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"aggregated_by","name":"aggregates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:6",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"associated_by","name":"associates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:7",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"created_by","name":"creates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:8",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"used_by","name":"uses","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:9",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"destroyed_by","name":"destroys","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:10",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"befriended_by","name":"befriends","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:11",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"instantiated_by","name":"instantiates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:12",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"declared_by","name":"declares","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("extension:test.extension/relation/taints",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived","proof"],"id":"relation/taints","inverse":"tainted_by","layer":"symbol","name":"taints","package":"test.extension","qualified_name":"test.extension/relation/taints","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_version',1);
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_hash',"268cc2ac7253ba94331d51e169cce6bd3124afe258e2b15a3236f246528872a8");
INSERT OR IGNORE INTO meta(key,value) VALUES ('artifact_kind','semantic-index');
INSERT OR IGNORE INTO meta(key,value) VALUES ('status','complete');
INSERT OR IGNORE INTO meta(key,value) VALUES ('trust','producer-verified');
INSERT OR IGNORE INTO meta(key,value) VALUES ('evidence','source');
