-- Generated by scripts/generate_catalogs.py; DO NOT EDIT.
INSERT OR IGNORE INTO symbol_kind(id,name) VALUES
  (2,"struct"),
  (3,"union"),
  (4,"class"),
  (5,"enum"),
  (6,"member"),
  (7,"enum-constant"),
  (8,"function"),
  (9,"variable"),
  (20,"typedef"),
  (21,"method"),
  (22,"namespace"),
  (24,"constructor"),
  (25,"destructor"),
  (30,"function-template"),
  (31,"class-template"),
  (36,"type-alias"),
  (501,"macro");
INSERT OR IGNORE INTO edge_kind(id,name) VALUES
  (1,"calls"),
  (2,"inherits"),
  (3,"contains"),
  (4,"specializes"),
  (5,"instantiates"),
  (6,"overrides"),
  (7,"uses"),
  (8,"field_of"),
  (9,"method_of"),
  (10,"construct-value"),
  (11,"construct-temp"),
  (12,"construct-heap"),
  (13,"construct-copy"),
  (14,"construct-move"),
  (15,"factory-construct"),
  (16,"destroy"),
  (17,"friend"),
  (18,"dispatch_calls"),
  (19,"alias_of"),
  (20,"of_type");
INSERT OR IGNORE INTO entity_edge_kind(id,name) VALUES
  (1,"generalizes"),
  (2,"implements"),
  (3,"specializes"),
  (4,"composes"),
  (5,"aggregates"),
  (6,"associates"),
  (7,"creates"),
  (8,"uses"),
  (9,"destroys"),
  (10,"befriends"),
  (11,"instantiates"),
  (12,"declares");
INSERT OR IGNORE INTO entity_kind(id,name) VALUES
  (0,"other"),
  (1,"class"),
  (2,"abstract_class"),
  (3,"interface"),
  (4,"union"),
  (5,"enum"),
  (6,"class_template"),
  (7,"abstract_class_template"),
  (8,"interface_template"),
  (9,"namespace");
INSERT OR IGNORE INTO type_kind(id,name) VALUES
  (1,"builtin"),
  (2,"record"),
  (3,"enum"),
  (4,"alias"),
  (5,"pointer"),
  (6,"lvalue-reference"),
  (7,"rvalue-reference"),
  (8,"array"),
  (9,"function"),
  (10,"template-param"),
  (11,"other"),
  (12,"member-data-pointer"),
  (13,"member-function-pointer");
INSERT OR IGNORE INTO type_edge_kind(id,name) VALUES
  (1,"pointee"),
  (2,"element_type"),
  (3,"alias_of"),
  (4,"return_type"),
  (5,"param_type"),
  (6,"template_argument_type"),
  (7,"member_owner"),
  (8,"member_component");
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_version',1);
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_hash',"a36486447a5b4d5cb1ad6e1a7248be623e56650ed44469e8e8131cd44eb2dc5e");
INSERT OR IGNORE INTO meta(key,value) VALUES ('artifact_kind','semantic-index');
INSERT OR IGNORE INTO meta(key,value) VALUES ('status','complete');
INSERT OR IGNORE INTO meta(key,value) VALUES ('trust','producer-verified');
INSERT OR IGNORE INTO meta(key,value) VALUES ('evidence','source');
