-- Generated by scripts/generate_catalogs.py; DO NOT EDIT.
INSERT OR IGNORE INTO symbol_kind(id,name) VALUES
  (2,"struct"),
  (3,"union"),
  (4,"class"),
  (5,"enum"),
  (6,"member"),
  (7,"enum-constant"),
  (8,"function"),
  (9,"variable"),
  (20,"typedef"),
  (21,"method"),
  (22,"namespace"),
  (24,"constructor"),
  (25,"destructor"),
  (30,"function-template"),
  (31,"class-template"),
  (36,"type-alias"),
  (501,"macro");
INSERT OR IGNORE INTO edge_kind(id,name) VALUES
  (1,"calls"),
  (2,"inherits"),
  (3,"contains"),
  (4,"specializes"),
  (5,"instantiates"),
  (6,"overrides"),
  (7,"uses"),
  (8,"field_of"),
  (9,"method_of"),
  (10,"construct-value"),
  (11,"construct-temp"),
  (12,"construct-heap"),
  (13,"construct-copy"),
  (14,"construct-move"),
  (15,"factory-construct"),
  (16,"destroy"),
  (17,"friend"),
  (18,"dispatch_calls"),
  (19,"alias_of"),
  (20,"of_type");
INSERT OR IGNORE INTO entity_edge_kind(id,name) VALUES
  (1,"generalizes"),
  (2,"implements"),
  (3,"specializes"),
  (4,"composes"),
  (5,"aggregates"),
  (6,"associates"),
  (7,"creates"),
  (8,"uses"),
  (9,"destroys"),
  (10,"befriends"),
  (11,"instantiates"),
  (12,"declares");
INSERT OR IGNORE INTO entity_kind(id,name) VALUES
  (0,"other"),
  (1,"class"),
  (2,"abstract_class"),
  (3,"interface"),
  (4,"union"),
  (5,"enum"),
  (6,"class_template"),
  (7,"abstract_class_template"),
  (8,"interface_template"),
  (9,"namespace");
INSERT OR IGNORE INTO type_kind(id,name) VALUES
  (1,"builtin"),
  (2,"record"),
  (3,"enum"),
  (4,"alias"),
  (5,"pointer"),
  (6,"lvalue-reference"),
  (7,"rvalue-reference"),
  (8,"array"),
  (9,"function"),
  (10,"template-param"),
  (11,"other"),
  (12,"member-data-pointer"),
  (13,"member-function-pointer");
INSERT OR IGNORE INTO type_edge_kind(id,name) VALUES
  (1,"pointee"),
  (2,"element_type"),
  (3,"alias_of"),
  (4,"return_type"),
  (5,"param_type"),
  (6,"template_argument_type"),
  (7,"member_owner"),
  (8,"member_component");
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:1",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site","declaration"],"inverse":"called_by","layer":"symbol","name":"calls","source":"symbol.callable","target":"symbol.callable","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:2",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"subclasses","layer":"symbol","name":"inherits","source":"symbol.record","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:3",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"contained_by","layer":"symbol","name":"contains","source":"symbol.scope","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:4",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration","reference_site"],"inverse":"specialized_by","layer":"symbol","name":"specializes","source":"symbol.declaration","target":"symbol.template","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:5",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration","reference_site"],"inverse":"instantiated_by","layer":"symbol","name":"instantiates","source":"symbol.declaration","target":"symbol.template","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:6",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"overridden_by","layer":"symbol","name":"overrides","source":"symbol.method","target":"symbol.method","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:7",'{"completeness":"partial","evidence":"reference_site","evidence_capabilities":["reference_site","call_site"],"inverse":"used_by","layer":"symbol","name":"uses","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:8",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"fields","layer":"symbol","name":"field_of","source":"symbol.member","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:9",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"methods","layer":"symbol","name":"method_of","source":"symbol.method","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:10",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"construct-value","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:11",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"construct-temp","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:12",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"construct-heap","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:13",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"construct-copy","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:14",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"construct-move","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:15",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"constructed_by","layer":"symbol","name":"factory-construct","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:16",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"destroyed_by","layer":"symbol","name":"destroy","source":"symbol.callable","target":"symbol.record","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:17",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"befriended_by","layer":"symbol","name":"friend","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:18",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site","derived"],"inverse":"dispatch_callers","layer":"symbol","name":"dispatch_calls","source":"symbol.callable","target":"symbol.callable","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:19",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"aliased_by","layer":"symbol","name":"alias_of","source":"symbol.alias","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:20",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"typed_by","layer":"symbol","name":"of_type","source":"symbol.declaration","target":"type","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:1",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"specialized_by","layer":"entity","name":"generalizes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:2",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"implemented_by","layer":"entity","name":"implements","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:3",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"specialized_by","layer":"entity","name":"specializes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:4",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"composed_by","layer":"entity","name":"composes","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:5",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"aggregated_by","layer":"entity","name":"aggregates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:6",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"associated_by","layer":"entity","name":"associates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:7",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"created_by","layer":"entity","name":"creates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:8",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"used_by","layer":"entity","name":"uses","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:9",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"destroyed_by","layer":"entity","name":"destroys","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:10",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"befriended_by","layer":"entity","name":"befriends","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:11",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"instantiated_by","layer":"entity","name":"instantiates","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:entity:12",'{"completeness":"complete","evidence":"derived","evidence_capabilities":["derived"],"inverse":"declared_by","layer":"entity","name":"declares","source":"entity","target":"entity","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:21",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration","call_site"],"inverse":"of_callable","layer":"symbol","name":"has_parameter","source":"symbol.callable","target":"parameter","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:22",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"of_template","layer":"symbol","name":"has_template_parameter","source":"symbol.template","target":"template_parameter","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:23",'{"completeness":"partial","evidence":"reference_site","evidence_capabilities":["reference_site","call_site"],"inverse":"of_template","layer":"symbol","name":"has_template_argument","source":"symbol.template","target":"template_argument","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:24",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"of_caller","layer":"symbol","name":"has_call_edge","source":"symbol.callable","target":"edge","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:symbol:25",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site","declaration"],"inverse":"of_symbol","layer":"symbol","name":"has_evidence","source":"symbol.callable","target":"evidence","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:parameter:1",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"has_parameter","layer":"parameter","name":"of_type","source":"parameter","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:parameter:2",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"has_declared_parameter","layer":"parameter","name":"declared_type","source":"parameter","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:parameter:3",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"has_adjusted_parameter","layer":"parameter","name":"adjusted_type","source":"parameter","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:parameter:4",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"referenced_by_parameter","layer":"parameter","name":"references_symbol","source":"parameter","target":"symbol","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:parameter:5",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"of_parameter","layer":"parameter","name":"has_evidence","source":"parameter","target":"evidence","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:template_parameter:1",'{"completeness":"complete","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"has_template_parameter","layer":"template_parameter","name":"of_type","source":"template_parameter","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:template_parameter:2",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"defaulted_by","layer":"template_parameter","name":"has_default","source":"template_parameter","target":"evidence","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:template_argument:1",'{"completeness":"partial","evidence":"reference_site","evidence_capabilities":["reference_site"],"inverse":"has_template_argument","layer":"template_argument","name":"of_type","source":"template_argument","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:template_argument:2",'{"completeness":"partial","evidence":"reference_site","evidence_capabilities":["reference_site"],"inverse":"referenced_by_template_argument","layer":"template_argument","name":"references_symbol","source":"template_argument","target":"symbol","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:edge:1",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"of_edge","layer":"edge","name":"has_argument","source":"edge","target":"call_argument","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:edge:2",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"of_edge","layer":"edge","name":"has_evidence","source":"edge","target":"evidence","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:call_argument:1",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"has_call_argument","layer":"call_argument","name":"of_type","source":"call_argument","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:call_argument:2",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"referenced_by_call_argument","layer":"call_argument","name":"references_symbol","source":"call_argument","target":"symbol","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:evidence:1",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"has_evidence","layer":"evidence","name":"of_edge","source":"evidence","target":"edge","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:evidence:2",'{"completeness":"partial","evidence":"call_site","evidence_capabilities":["call_site"],"inverse":"has_evidence","layer":"evidence","name":"of_occurrence","source":"evidence","target":"call_argument","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:type:1",'{"completeness":"partial","evidence":"declaration","evidence_capabilities":["declaration"],"inverse":"of_type","layer":"type","name":"references_symbol","source":"type","target":"symbol","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("relation:type:2",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived"],"inverse":"of_type_edge","layer":"type","name":"has_type_edge","source":"type","target":"type","traversal":["out","in"],"virtual":true}');
INSERT OR IGNORE INTO meta(key,value) VALUES ("extension:test.extension/relation/taints",'{"completeness":"partial","evidence":"derived","evidence_capabilities":["derived","proof"],"id":"relation/taints","inverse":"tainted_by","layer":"symbol","name":"taints","package":"test.extension","qualified_name":"test.extension/relation/taints","source":"symbol.declaration","target":"symbol.declaration","traversal":["out","in"]}');
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_version',1);
INSERT OR IGNORE INTO meta(key,value) VALUES ('catalog_hash',"1adb5f6663a2e48dc3a624c79703ceaa5287f2784731a00bbc469dba8d5935d4");
INSERT OR IGNORE INTO meta(key,value) VALUES ('artifact_kind','semantic-index');
INSERT OR IGNORE INTO meta(key,value) VALUES ('status','complete');
INSERT OR IGNORE INTO meta(key,value) VALUES ('trust','producer-verified');
INSERT OR IGNORE INTO meta(key,value) VALUES ('evidence','source');
