"""Read/query parity against an index generated by the C++ cidx binary."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

from indexer.queryplan import Executor, codebase, count, eq, nodes, start
from indexer.storage import Storage


REPO_ROOT = Path(__file__).resolve().parents[2]


def test_python_reads_cpp_generated_index_and_identity(tmp_path):
    project = tmp_path / "project"
    project.mkdir()
    (project / "fixture.cpp").write_text(
        "int parity_reader_symbol() { return 1; }\n", encoding="utf-8"
    )
    (project / "compile_commands.json").write_text(
        json.dumps(
            [
                {
                    "directory": str(project),
                    "command": "c++ -std=c++23 -c fixture.cpp -o fixture.o",
                    "file": "fixture.cpp",
                }
            ]
        ),
        encoding="utf-8",
    )

    cidx = REPO_ROOT / "build" / "cidx"
    assert cidx.is_file(), "build/cidx must exist for the C++ reader fixture"
    cache = tmp_path / "cache"
    cache.mkdir()
    env = dict(os.environ, INDEXER_CACHE=str(cache))
    for args in (("import", "--db", str(project)), ("index",)):
        result = subprocess.run(
            [str(cidx), *args],
            cwd=REPO_ROOT,
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stdout + result.stderr

    with Storage(str(cache / "index.db")) as db:
        identity = db.index_identity()
        assert identity.freshness == "current"
        assert identity.source_revision is not None

        matches = db.lookup_symbols_by_name("parity_reader_symbol")
        assert [match.spelling for match in matches] == ["parity_reader_symbol"]

        executor = Executor(db)
        result = executor.run(
            (start(codebase()) | nodes(eq("spelling", "parity_reader_symbol"))).plan
        )
        assert result.index.freshness == "current"
        assert len(result.rows) == 1
        assert not result.truncated
        assert list(result.to_dict()) == [
            "shape",
            "view",
            "count",
            "truncated",
            "index",
            "rows",
        ]

        scalar = executor.run(
            (
                start(codebase())
                | nodes(eq("spelling", "parity_reader_symbol"))
                | count()
            ).plan
        )
        assert scalar.scalar == 1
        assert list(scalar.to_dict()) == [
            "shape",
            "view",
            "count",
            "truncated",
            "index",
        ]
