# Embed the canonical Souffle rule files (python/indexer/rules/*.dl) into a
# generated C++ header so the cidx binary carries the exact same bytes as the
# Python implementation.  Invoked at build time:
#   cmake -DRULES_DIR=<dir> -DOUT=<header> -P cmake/embed_dl.cmake
if(NOT DEFINED RULES_DIR OR NOT DEFINED OUT)
  message(FATAL_ERROR "embed_dl.cmake requires -DRULES_DIR=... and -DOUT=...")
endif()

set(_names prelude callgraph cycles unused)
set(_content "// Generated by cmake/embed_dl.cmake from python/indexer/rules.\n")
string(APPEND _content "// Do not edit; the .dl files are the single source of truth.\n")
string(APPEND _content "#pragma once\n\n#include <string_view>\n\n")
string(APPEND _content "namespace cidx::cli::dlrules {\n\n")
foreach(_name IN LISTS _names)
  file(READ "${RULES_DIR}/${_name}.dl" _body)
  string(APPEND _content "inline constexpr std::string_view k_${_name} = R\"__dl__(${_body})__dl__\";\n\n")
endforeach()
string(APPEND _content "} // namespace cidx::cli::dlrules\n")

file(WRITE "${OUT}.tmp" "${_content}")
configure_file("${OUT}.tmp" "${OUT}" COPYONLY)
file(REMOVE "${OUT}.tmp")
